sudo: required

services:
  - docker

language: java
dist: bionic

jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master

env:
  global:
    - DOCKER_IMAGE=mag20/sequence-service
    - DOCKER_TAG=$TRAVIS_JOB_NUMBER

jobs:
  include:
    - stage: mvn build
      script:
        - mvn clean package -U
    - stage: docker build
      script:
        - docker build -t "$DOCKER_IMAGE":latest .
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker tag "$DOCKER_IMAGE":latest "$DOCKER_IMAGE":"$DOCKER_TAG"
        - docker push "$DOCKER_IMAGE":latest
        - docker push "$DOCKER_IMAGE":"$DOCKER_TAG"
        - echo "$DOCKER_IMAGE":"$DOCKER_TAG"
        - echo "$DOCKER_IMAGE":latest