kumuluzee:
  name: mag2020-sequence-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8009
    http:
      port: 8009
  datasources:
    - jndi-name: jdbc/SequenceDB
      connection-url: jdbc:mysql://mag2020.cd0nfxw2grsa.eu-central-1.rds.amazonaws.com:3306/Sequence
      username: admin_uros
      password: admin_uros123
      max-pool-size: 20
  grpc:
    server:
      url: localhost
      http:
        port: 9006